#config_version=6

# Base mode that starts at the beginning of each ball
# and stops at the end of each ball.

mode:
  start_events: ball_starting
  stop_events: ball_will_end
  priority: 100

event_player:
  mode_base_started:
    - start_mode_bumpers
    - turn_on_rollovers
    - reset_bonus_tracker
    - disable_score_bonus
    - disable_white_bonus
    - disable_special
    - turn_on_1k_lights
    - reset_drop_targets
  mode_base_will_stop:
    - stop_mode_bumpers

  #handle adding to bonus and updating lights, also checks if it should enable top right bonus shot
  add_bonus{current_player.bonus < 29_000}:
    - add_bonus_1000
    - show_bonus_light
    - check_bonus_enabled

  add_extra_bonus: add_bonus

  #handle target hits
  shot_upper_left_extra_ball_hit{current_player.upper_left_extra_ball_enabled==1}: 
    - turn_off_upper_left_extra_ball_light
    - disable_upper_left_extra_ball
    - turn_on_shoot_again_light
    - award_extra_ball

  shot_inlanes_hit: 
    - score_500
    - add_bonus
    - turn_on_spinner_bonus_enabled_light
   
  #handle spinner hits
  spinner_spin_middle_spinner_hit: score_100
  spinner_spin_middle_spinner_hit{current_player.spinner_bonus_enabled==1}: add_bonus
    
  #handle showing the bonus light
  show_bonus_light{current_player.bonus_tracker < 40_000}:
    - turn_off_bonus_lights
    - handle_20k_light
    - handle_10k_light
    - turn_on_1k_lights
  handle_20k_light{current_player.bonus_tracker >= 20_000}:
    - turn_on_20k_light
    - decrement_bonus_tracker_20k
  handle_10k_light{current_player.bonus_tracker >= 10_000}:
    - turn_on_10k_light
    - decrement_bonus_tracker_10k

  check_bonus_enabled{current_player.bonus >= 20_000} :
    - enable_score_bonus
    - turn_on_bonus_enabled_light

  shot_score_bonus_hit{current_player.score_bonus_enabled==1}:
    - score_bonus
    - reset_bonus
    - reset_bonus_tracker
    - show_bonus_light
    - disable_score_bonus
    - turn_off_bonus_enabled_light

  shot_special_target_hit{current_player.free_game_awarded==0}:
    - disable_special
    - turn_off_special_light
    - enable_free_game_awarded

  #handle multiplier hits
  shot_multiplier_enable_unlit_hit: 
    - turn_on_multiplier_enable_light
    - set_multiplier_enabled
  shot_multiplier_enable_lit_hit: disable_multiplier
  disable_multiplier:
    - turn_off_multiplier_enable_light
    - set_multiplier_disabled

  #handle lanes
  #handle upper left lane
  shot_500_add_bonus_hit:
    - score_500
    - add_bonus
  shot_3000_point_lane_hit:
    - score_3_000
  shot_10_000_point_lane_hit:
    - score_10_000
  shot_500_point_letter_lane_hit:
    - score_500
  
  
  #handle gold/ship lane events
  shot_g_lane_unlit_hit: turn_on_g_lane_lights
  shot_o_lane_unlit_hit: turn_on_o_lane_lights
  shot_l_lane_unlit_hit: turn_on_l_lane_lights
  shot_d_lane_unlit_hit: turn_on_d_lane_lights
  sg_gold_lanes_lit_complete:
    - enable_upper_left_extra_ball
    - turn_on_upper_left_extra_ball_light
  turn_off_lane_lights: turn_off_g_lane_lights, turn_off_o_lane_lights, turn_off_l_lane_lights, turn_off_d_lane_lights
  turn_on_lane_lights: turn_on_g_lane_lights, turn_on_o_lane_lights, turn_on_l_lane_lights, turn_on_d_lane_lights

  #reset drop targets
  reset_drop_targets:
    - reset_middle_drop_targets
    - reset_upper_left_drop_targets

  #handle drop targets
  sg_middle_drop_targets_hit:
    - score_2_000
    - add_bonus
  sg_middle_drop_targets_hit{current_player.multiplier_enabled==1}:
    - increment_multiplier_level
    - turn_off_multiplier_lights
    - show_multiplier_light
    - disable_multiplier
  sg_white_drop_targets_hit:
    - score_2_000
    - add_bonus
  sg_white_drop_targets_hit{current_player.white_bonus_enabled==1}: #add an extra 3k and 2 bonus if white bonus is enabled to make it 5k and 3 bonus total
    - score_3_000
    - add_bonus
    - add_extra_bonus
  sg_red_drop_targets_hit:
    - score_2_000
    - add_bonus
  sg_red_drop_targets_complete:
    - reset_upper_left_drop_targets
  sg_red_drop_targets_complete{current_player.free_game_awarded==0}:
    - enable_special
    - turn_on_special_light
  sg_white_drop_targets_complete:
    - reset_upper_left_drop_targets
    - enable_white_bonus
    - turn_on_white_bonus_light
  

#LIGHT PLAYER SECTION
light_player:
  turn_on_rollovers: l_top_upper_left_bonus_rollover, l_middle_upper_left_bonus_rollover, l_bottom_upper_left_bonus_rollover, l_left_inlane_rollover, l_right_inlane_rollover
  turn_on_upper_left_extra_ball_light: l_upper_left_extra_ball_enabled
  turn_off_upper_left_extra_ball_light:
    l_upper_left_extra_ball_enabled:
      color: stop
  #lane lights
  turn_on_g_lane_lights: l_g_upper_lane, l_s_lower_lane
  turn_on_o_lane_lights: l_o_upper_lane, l_h_lower_lane
  turn_on_l_lane_lights: l_l_upper_lane, l_i_lower_lane
  turn_on_d_lane_lights: l_d_upper_lane, l_p_lower_lane
  turn_off_g_lane_lights: 
    l_g_upper_lane:
      color: stop
    l_s_lower_lane:
      color: stop
  turn_off_o_lane_lights: 
    l_o_upper_lane:
      color: stop
    l_h_lower_lane:
      color: stop
  turn_off_l_lane_lights: 
    l_l_upper_lane:
      color: stop
    l_i_lower_lane:
      color: stop
  turn_off_d_lane_lights: 
    l_d_upper_lane:
      color: stop
    l_p_lower_lane:
      color: stop

  #multiplier lights
  turn_on_multiplier_enable_light: l_advance_multiplier
  turn_off_multiplier_enable_light: 
    l_advance_multiplier:
      color: stop
  show_multiplier_light{current_player.multiplier_level==2}: l_2x_multiplier
  show_multiplier_light{current_player.multiplier_level==3}: l_3x_multiplier
  show_multiplier_light{current_player.multiplier_level==4}: l_4x_multiplier
  show_multiplier_light{current_player.multiplier_level==5}: l_5x_multiplier
  turn_off_multiplier_lights:
    l_2x_multiplier:
      color: stop
    l_3x_multiplier:
      color: stop
    l_4x_multiplier:
      color: stop
    l_5x_multiplier:
      color: stop

  #bonus lights
  turn_off_bonus_lights:
    l_1k_bonus:
      color: stop
    l_2k_bonus:
      color: stop
    l_3k_bonus:
      color: stop
    l_4k_bonus:
      color: stop
    l_5k_bonus:
      color: stop
    l_6k_bonus:
      color: stop
    l_7k_bonus:
      color: stop
    l_8k_bonus:
      color: stop
    l_9k_bonus:
      color: stop
    l_10k_bonus:
      color: stop
    l_20k_bonus:
      color: stop
  turn_on_bonus_lights: l_1k_bonus, l_2k_bonus, l_3k_bonus, l_4k_bonus, l_5k_bonus, l_6k_bonus, l_7k_bonus, l_8k_bonus, l_9k_bonus, l_10k_bonus, l_20k_bonus
  turn_on_20k_light: l_20k_bonus
  turn_on_10k_light: l_10k_bonus
  turn_on_1k_lights{current_player.bonus_tracker==1_000}: l_1k_bonus
  turn_on_1k_lights{current_player.bonus_tracker==2_000}: l_2k_bonus
  turn_on_1k_lights{current_player.bonus_tracker==3_000}: l_3k_bonus
  turn_on_1k_lights{current_player.bonus_tracker==4_000}: l_4k_bonus
  turn_on_1k_lights{current_player.bonus_tracker==5_000}: l_5k_bonus
  turn_on_1k_lights{current_player.bonus_tracker==6_000}: l_6k_bonus
  turn_on_1k_lights{current_player.bonus_tracker==7_000}: l_7k_bonus
  turn_on_1k_lights{current_player.bonus_tracker==8_000}: l_8k_bonus
  turn_on_1k_lights{current_player.bonus_tracker==9_000}: l_9k_bonus
  
  turn_on_bonus_enabled_light: l_score_bonus_enabled
  turn_off_bonus_enabled_light: 
    l_score_bonus_enabled:
      color: stop

  turn_on_spinner_bonus_enabled_light: l_spinner_bonus_enabled
  turn_off_spinner_bonus_enabled_light: 
    l_spinner_bonus_enabled:
      color: stop

  turn_on_shoot_again_light: l_shoot_again_enabled
  turn_off_shoot_again_light:
    l_shoot_again_enabled:
      color: stop
    
  turn_on_special_light: l_special_enabled
  turn_off_special_light:
    l_special_enabled:
      color: stop

  turn_on_white_bonus_light: l_white_drop_target_bonus_enabled
  turn_off_white_bonus_light:
    l_white_drop_target_bonus_enabled:
      color: stop

shots:
  
  #lane shots
  shot_inlanes:
    switches: s_left_inlane_rollover, s_right_inlane_rollover
  shot_500_add_bonus:
    switches: s_upper_left_lane, s_right_inner_lane, s_middle_left_target, s_upper_left_extra_ball, s_upper_right_shooter_return_lane
  shot_3000_point_lane:
    switches: s_left_50_50_lane, s_right_outer_lane

  #gold/ship lane shots
  shot_g_lane:
    switches: s_g_upper_lane, s_s_lower_lane
  shot_o_lane:
    switches: s_o_upper_lane, s_h_lower_lane
  shot_l_lane:
    switches: s_l_upper_lane, s_i_lower_lane
  shot_d_lane:
    switches: s_d_upper_lane, s_p_lower_lane
  shot_500_point_letter_lane: 
    switches: s_g_upper_lane, s_o_upper_lane, s_l_upper_lane, s_d_upper_lane, s_s_lower_lane, s_h_lower_lane, s_i_lower_lane, s_p_lower_lane

  #multiplier enable bumpers & rollovers
  shot_multiplier_enable:
    switches: s_lower_left_bumper, s_upper_left_bumper, s_upper_right_bumper, s_top_upper_left_bonus_rollover, s_middle_upper_left_bonus_rollover, s_bottom_upper_left_bonus_rollover
    profile: sp_on_off_loop
    reset_events: disable_multiplier

  #bonus or multipler (if bonus multipler lit) drop targets
  shot_middle_drop_target_1:
    switch: s_middle_drop_target_1
  shot_middle_drop_target_2:
    switch: s_middle_drop_target_2
  shot_middle_drop_target_3:
    switch: s_middle_drop_target_3
  shot_middle_drop_target_4:
    switch: s_middle_drop_target_4

  #top left_drop targets
  #red
  shot_red_drop_target_1:
    switch: s_red_drop_target_1
  shot_red_drop_target_2:
    switch: s_red_drop_target_2
  shot_red_drop_target_3:
    switch: s_red_drop_target_3
  shot_red_drop_target_4:
    switch: s_red_drop_target_4
  #white
  shot_white_drop_target_1:
    switch: s_white_drop_target_1
  shot_white_drop_target_2:
    switch: s_white_drop_target_2
  shot_white_drop_target_3:
    switch: s_white_drop_target_3


#stand up target shots
  shot_upper_left_extra_ball:
    switches: s_upper_left_extra_ball
  shot_middle_right_extra_ball:
    switches: s_middle_right_extra_ball
  shot_special_target:
    switches: s_special_target
  
  shot_score_bonus:
    switches: s_score_bonus_kicker

shot_groups:
  sg_gold_lanes: 
    shots: shot_g_lane, shot_o_lane, shot_l_lane, shot_d_lane
    reset_events: turn_off_upper_lane_lights
  sg_middle_drop_targets:
    shots: shot_middle_drop_target_1, shot_middle_drop_target_2, shot_middle_drop_target_3, shot_middle_drop_target_4
  sg_white_drop_targets:
    shots: shot_white_drop_target_1, shot_white_drop_target_2, shot_white_drop_target_3
  sg_red_drop_targets:
    shots: shot_red_drop_target_1, shot_red_drop_target_2, shot_red_drop_target_3, shot_red_drop_target_4
   
shot_profiles:
  sp_on_off_loop:
    advance_on_hit: true
    loop: true
    states: 
      - name: unlit
        show: "off"
      - name: lit
        show: "on"

slide_player:
  mode_base_started: base_slide

variable_player:
  set_multiplier_enabled:
    multiplier_enabled:
      int: 1
      action: set
  set_multiplier_disabled:
    multiplier_enabled:
      int: 0
      action: set
  increment_multiplier_level{current_player.multiplier_level < 5}: #multiplier level is capped at 5
    multiplier_level: 1
  
  #add 1000 to bonus and set the bonus tracker equal to the new bonus value
  add_bonus_1000:
    bonus: 1000
    bonus_tracker:
      int: current_player.bonus
      action: set

  #add to score
  score_100:
    score: 100
  score_500:
    score: 500
  score_2_000:
    score: 2_000
  score_3_000:
    score: 3_000
  score_10_000:
    score: 10_000

  #set the bonus_tracker equal to the current_player.bonus so you can decrement it as needed to display the 20k and 10k lights as well as one of the 1k lights
  set_bonus_tracker:
    bonus_tracker:
      int: current_player.bonus
      action: set
  reset_bonus_tracker:
    bonus_tracker:
      int: 1_000
      action: set

  #turns spinner bonus on/off
  enable_spinner_bonus:
    spinner_bonus_enabled:
      int: 1
      action: set
  disable_spinner_bonus:
    spinner_bonus_enabled:
      int: 0
      action: set

  #bonus tracker allows us to keep track of bonus lights without affecting the actual bonus value
  decrement_bonus_tracker_20k:
    bonus_tracker:
      int: current_player.bonus_tracker - 20_000
      action: set
  decrement_bonus_tracker_10k:
    bonus_tracker:
      int: current_player.bonus_tracker - 10_000
      action: set

  #score bonus flag
  enable_score_bonus:
    score_bonus_enabled:
      int: 1
      action: set
  disable_score_bonus:
    score_bonus_enabled:
      int: 0
      action: set
  
  score_bonus:
    score: current_player.bonus * current_player.multiplier_level
  reset_bonus:
    bonus:
      int: 1000
      action: set

  #upper left extra ball flag
  enable_upper_left_extra_ball:
    upper_left_extra_ball_enabled:
      int: 1
      action: set
  disable_upper_left_extra_ball:
    upper_left_extra_ball_enabled:
      int: 1
      action: set

  #white bonus
  enable_white_bonus:
    white_bonus_enabled:
      int: 1
      action: set
  disable_white_bonus:
    white_bonus_enabled:
      int: 0
      action: set

  #special
  enable_special:
    special_enabled:
      int: 1
      action: set
  disable_special:
    special_enabled:
      int: 0
      action: set
  enable_free_game_awarded:
    free_game_awarded:
      int: 1
      action: set
  disable_free_game_awarded:
    free_game_awarded:
      int: 0
      action: set
  

#EXTRA BALLS
extra_balls:
  eb_extra_ball:
    award_events: award_extra_ball
    max_per_game: 3