#config_version=6

# Base mode that starts at the beginning of each ball
# and stops at the end of each ball.

mode:
  start_events: ball_starting
  stop_events: ball_will_end
  priority: 100

event_player:
  mode_base_started:
    - start_mode_bumpers
    - turn_on_upper_left_rollovers
  mode_base_will_stop:
    - stop_mode_bumpers
  sg_upper_lanes_lit_complete:
    - turn_on_extra_ball_light
    - turn_off_upper_lane_lights
  shot_extra_ball_hit: turn_off_extra_ball_light
  shot_multiplier_enable_unlit_hit: 
    - turn_on_multiplier_enable_light
    - set_multiplier_enabled
  shot_multiplier_enable_lit_hit: disable_multiplier
  disable_multiplier:
    - turn_off_multiplier_enable_light
    - set_multiplier_disabled
  sg_middle_drop_targets_hit{current_player.multiplier_enabled==1}:
    - increment_multiplier_level
    - show_multiplier_light
    - disable_multiplier



light_player:
  turn_on_upper_left_rollovers: l_top_upper_left_bonus_rollover, l_middle_upper_left_bonus_rollover, l_bottom_upper_left_bonus_rollover
  turn_on_extra_ball_light:
    l_extra_ball_enable:
      color: red
  turn_off_extra_ball_light:
    l_extra_ball_enable:
      color: stop
  turn_off_upper_lane_lights:
    l_g_lane:
      color: stop
    l_o_lane:
      color: stop
    l_l_lane:
      color: stop
    l_d_lane:
      color: stop
  turn_on_multiplier_enable_light: l_lower_wanted_dead_or_alive
  turn_off_multiplier_enable_light: 
    l_lower_wanted_dead_or_alive:
      color: stop
  show_multiplier_light{current_player.multiplier_level==2}: l_2x_multiplier
  show_multiplier_light{current_player.multiplier_level==3}: l_3x_multiplier
  show_multiplier_light{current_player.multiplier_level==4}: l_4x_multiplier
  show_multiplier_light{current_player.multiplier_level==5}: l_5x_multiplier

shots:
  
  #gold shots
  shot_g_lane:
    switches: s_g_lane
    show_tokens:
      leds: l_g_lane
  shot_o_lane:
    switches: s_o_lane
    show_tokens:
      leds: l_o_lane
  shot_l_lane:
    switches: s_l_lane
    show_tokens:
      leds: l_l_lane
  shot_d_lane:
    switches: s_d_lane
    show_tokens:
      leds: l_d_lane

  #extra ball shot
  shot_extra_ball:
    switches: s_extra_ball

  #multiplier enable bumpers & rollovers
  shot_multiplier_enable:
    switches: s_lower_left_bumper, s_upper_left_bumper, s_upper_right_bumper, s_top_upper_left_bonus_rollover, s_middle_upper_left_bonus_rollover, s_bottom_upper_left_bonus_rollover
    profile: sp_on_off_loop
    reset_events: disable_multiplier

  #bonus or multipler (if bonus multipler lit) drop targets
  shot_middle_drop_target_1:
    switch: s_middle_drop_target_1
  shot_middle_drop_target_2:
    switch: s_middle_drop_target_2
  shot_middle_drop_target_3:
    switch: s_middle_drop_target_3
  shot_middle_drop_target_4:
    switch: s_middle_drop_target_4
  
shot_groups:
  sg_upper_lanes: 
    shots: shot_g_lane, shot_o_lane, shot_l_lane, shot_d_lane
    reset_events: turn_off_upper_lane_lights
  sg_middle_drop_targets:
    shots: shot_middle_drop_target_1, shot_middle_drop_target_2, shot_middle_drop_target_3, shot_middle_drop_target_4
   
shot_profiles:
  sp_on_off_loop:
    advance_on_hit: true
    loop: true
    states: 
      - name: unlit
        show: "off"
      - name: lit
        show: "on"


slide_player:
  mode_base_started: base_slide

variable_player:
  set_multiplier_enabled:
    multiplier_enabled:
      int: 1
      action: set
  set_multiplier_disabled:
    multiplier_enabled:
      int: 0
      action: set
  increment_multiplier_level{current_player.multiplier_level < 5}: #multiplier level is capped at 5
    multiplier_level: 1