#config_version=6

switches:
  #gold lanes switches
  s_g_lane:
    number:
  s_o_lane:
    number:
  s_l_lane:
    number:
  s_d_lane:
    number:
  s_extra_ball:
    number:

  #bumper switches
  s_lower_left_bumper:
    number:
  s_upper_left_bumper:
    number:
  s_upper_right_bumper:
    number:

  #rollover switches
  s_top_upper_left_bonus_rollover:
    number:
  s_middle_upper_left_bonus_rollover:
    number:
  s_bottom_upper_left_bonus_rollover:
    number:  

  #drop targets
  s_middle_drop_target_1:
    number:
  s_middle_drop_target_2:
    number:
  s_middle_drop_target_3:
    number:
  s_middle_drop_target_4:
    number:        

  #sling shot
  s_sling_left:
    number:    

  # Cabinet Switches
  s_flipper_left:
    number:
    tags: left_flipper
  s_flipper_right:
    number:
    tags: right_flipper
  s_start:
    number:
    tags: start
  # Trough Switches
  s_trough_1:
    number:
  s_trough_2:
    number:
  s_trough_3:
    number:
  s_plunger_lane:
    number:
