#config_version=6

lights:
  #lane lights
  l_a_upper_lane:
    number:
  l_b_upper_lane:
    number:
  l_c_upper_lane:
    number:
  l_d_upper_lane:
    number:
  l_a_lower_lane:
    number:
  l_b_lower_lane:
    number:
  l_c_lower_lane:
    number:
  l_d_lower_lane:
    number:

  #bonus lights
  l_1k_bonus:
    number:
  l_2k_bonus:
    number:
  l_3k_bonus:
    number:
  l_4k_bonus:
    number:
  l_5k_bonus:
    number:
  l_6k_bonus:
    number:
  l_7k_bonus:
    number:
  l_8k_bonus:
    number:
  l_9k_bonus:
    number:
  l_10k_bonus:
    number:
  l_20k_bonus:
    number:
    
  #bonus unlock lights
  l_score_bonus_enabled:
    number:
  l_spinner_bonus_enabled:
    number:
  l_white_drop_target_bonus_enabled:
    number:
  l_upper_left_extra_ball_enabled:
    number:
  l_right_extra_ball_enabled:
    number:
  l_special_enabled:
    number:
  l_shoot_again_enabled:
    number:

  
  #multiplier lights
  l_advance_multiplier:
    number:
  l_2x_multiplier:
    number:
  l_3x_multiplier:
    number:
  l_4x_multiplier:
    number:
  l_5x_multiplier:
    number:

  #rollover_lights
  l_top_upper_left_bonus_rollover:
    number:
  l_middle_upper_left_bonus_rollover:
    number:
  l_bottom_upper_left_bonus_rollover:
    number:
  l_left_inlane_rollover:
    number:
  l_right_inlane_rollover:
    number:
