#config_version=6

drop_targets:
  dt_middle_1:
    switch: s_middle_drop_target_1
  dt_middle_2:
    switch: s_middle_drop_target_2
  dt_middle_3:
    switch: s_middle_drop_target_3
  dt_middle_4:
    switch: s_middle_drop_target_4