#config_version=6

  player_vars:
    multiplier_enabled: #true = 1, false = 0, used to turn on advance multiplier light. If it's true, you can increment the multipler lights.
      value_type: int
      initial_value: 0
    multiplier_level: #starts at 1x multiplier, can be incremented up to 5x multiplier. Gets incremented 1 level at a time
      value_type: int
      initial_value: 1
    bonus:
      value_type: int
      initial_value: 1000
    bonus_tracker: #used to calculate which bonus lights should be on
      value_type: int
      initial_value: 1000
    score_bonus_enabled:
      value_type: int
      initial_value: 0
    spinner_bonus_enabled:
      value_type: int
      initial_value: 0
    enable_upper_left_extra_ball:
      value_type: int
      initial_value: 0
    white_bonus_enabled:
      value_type: int
      initial_value: 0
    special_enabled:
      value_type: int
      initial_value: 0
    free_game_awarded:
      value_type: int
      initial_value: 0