#config_version=6

#NOTE: includes switches and a spinner at the bottom of the page

switches:
  #lane switches
  s_upper_left_lane:
    number:
  s_right_inner_lane:
    number:
  s_right_outer_lane:
    number:
  s_right_outer_drain_lane:
    number:
  s_left_outer_drain_lane:
    number:
  s_left_50_50_lane:
    number:
  s_left_inner_lane:
    number:
  s_upper_right_shooter_return_lane:
    number:
  

  #gold/ship lanes switches, these are paired together so g activates like s 
  s_g_upper_lane:
    number:
  s_o_upper_lane:
    number:
  s_l_upper_lane:
    number:
  s_d_upper_lane:
    number:
  s_s_lower_lane:
    number:
  s_h_lower_lane:
    number:
  s_i_lower_lane:
    number:
  s_p_lower_lane:
    number:

  #bumper switches
  s_lower_left_bumper:
    number:
  s_upper_left_bumper:
    number:
  s_upper_right_bumper:
    number:

  #rollover switches
  s_top_upper_left_bonus_rollover:
    number:
  s_middle_upper_left_bonus_rollover:
    number:
  s_bottom_upper_left_bonus_rollover:
    number:  
  s_left_inlane_rollover:
    number:
  s_right_inlane_rollover:
    number:

  #drop targets
  s_middle_drop_target_1:
    number:
  s_middle_drop_target_2:
    number:
  s_middle_drop_target_3:
    number:
  s_middle_drop_target_4:
    number:
  s_red_drop_target_1:
    number:
  s_red_drop_target_2:
    number:
  s_red_drop_target_3:
    number:
  s_red_drop_target_4:
    number:
  s_white_drop_target_1:
    number:
  s_white_drop_target_2:
    number:
  s_white_drop_target_3:
    number:


  #stand up targets
  s_upper_left_extra_ball:
    number:
    # debounce: normal
    # ignore_window_ms: 1000ms
  s_middle_left_target:
    number:
    # debounce: normal
    # ignore_window_ms: 1000ms
  s_middle_right_extra_ball:
    number:
    # debounce: normal
    # ignore_window_ms: 1000ms
  s_special_target:
    number:
    # debounce: normal
    # ignore_window_ms: 1000ms

  s_score_bonus_kicker:
    number:


  #spinner switch
  s_middle_spinner:
    number:


  #sling shot
  s_sling_left:
    number:    

  # Cabinet Switches
  s_flipper_left:
    number:
    tags: left_flipper
  s_flipper_right:
    number:
    tags: right_flipper
  s_start:
    number:
    tags: start

  # Trough Switches
  s_trough_1:
    number:
  s_trough_2:
    number:
  s_trough_3:
    number:
  s_plunger_lane:
    number:

  #drain switch
  s_drain:
    number:

#SPINNER SECTION
spinners:
  spin_middle_spinner:
    switch: s_middle_spinner
    active_ms: 500